# SlidingBlockAnalysis { #pyslammer.SlidingBlockAnalysis }

```python
SlidingBlockAnalysis(self, ky, a_in, dt, scale_factor=1.0, target_pga=None)
```

Base class for all time-domain sliding block analyses.

## Methods

| Name | Description |
| --- | --- |
| [sliding_block_plot](#pyslammer.SlidingBlockAnalysis.sliding_block_plot) | Plot the analysis result as a 3-by-1 array of time series figures. |

### sliding_block_plot { #pyslammer.SlidingBlockAnalysis.sliding_block_plot }

```python
SlidingBlockAnalysis.sliding_block_plot(sliding_vel_mode=True, fig=None)
```

Plot the analysis result as a 3-by-1 array of time series figures.
From top to bottom, the figures contain: acceleration, velocity, and displacement signals. By default, the acceleration figure shows the input acceleration and the block acceleration. The velocity figure shows the *sliding* (i.e., relative to the input motion) velocity of the block. If desired, `sliding_vel_mode` can be set to `False` to display the absolute velocity of the input motion and the block. The displacement figure shows the relative displacement of the block to the base.