# Function reference {.doc .doc-index}

## pyslammer



| | |
| --- | --- |
| [G_EARTH](G_EARTH.qmd#pyslammer.G_EARTH) |  |
| [SlidingBlockAnalysis](SlidingBlockAnalysis.qmd#pyslammer.SlidingBlockAnalysis) |  |
| [M_TO_CM](M_TO_CM.qmd#pyslammer.M_TO_CM) |  |
| [RigidAnalysis](RigidAnalysis.qmd#pyslammer.RigidAnalysis) | Rigid Block Analysis. |
| [mod_damp_testing](mod_damp_testing.qmd#pyslammer.mod_damp_testing) |  |
| [strain_mod_update](strain_mod_update.qmd#pyslammer.strain_mod_update) |  |
| [strain_damp_update](strain_damp_update.qmd#pyslammer.strain_damp_update) |  |
| [impedance_damping](impedance_damping.qmd#pyslammer.impedance_damping) |  |
| [constant_k_y](constant_k_y.qmd#pyslammer.constant_k_y) |  |
| [interpolated_k_y](interpolated_k_y.qmd#pyslammer.interpolated_k_y) |  |
| [assign_k_y](assign_k_y.qmd#pyslammer.assign_k_y) |  |
| [Decoupled](Decoupled.qmd#pyslammer.Decoupled) |  |
| [mrd_testing](mrd_testing.qmd#pyslammer.mrd_testing) |  |
| [equivalent_linear_testing](equivalent_linear_testing.qmd#pyslammer.equivalent_linear_testing) |  |
| [k_y_testing](k_y_testing.qmd#pyslammer.k_y_testing) |  |
| [some_ky_func](some_ky_func.qmd#pyslammer.some_ky_func) |  |
| [strains](strains.qmd#pyslammer.strains) |  |
| [mod_reduction](mod_reduction.qmd#pyslammer.mod_reduction) |  |
| [damping](damping.qmd#pyslammer.damping) |  |
| [darendelli](darendelli.qmd#pyslammer.darendelli) |  |
| [histories](histories.qmd#pyslammer.histories) |  |
| [ky_const](ky_const.qmd#pyslammer.ky_const) |  |
| [ky_interp](ky_interp.qmd#pyslammer.ky_interp) |  |
| [ky_func](ky_func.qmd#pyslammer.ky_func) |  |
| [motion](motion.qmd#pyslammer.motion) |  |
| [t_step](t_step.qmd#pyslammer.t_step) |  |
| [input_acc](input_acc.qmd#pyslammer.input_acc) |  |
| [da](da.qmd#pyslammer.da) |  |
| [FT_TO_IN](FT_TO_IN.qmd#pyslammer.FT_TO_IN) |  |
| [FT_TO_M](FT_TO_M.qmd#pyslammer.FT_TO_M) |  |
| [FT3_TO_IN3](FT3_TO_IN3.qmd#pyslammer.FT3_TO_IN3) |  |
| [CM_TO_FT](CM_TO_FT.qmd#pyslammer.CM_TO_FT) |  |
| [CM_TO_IN](CM_TO_IN.qmd#pyslammer.CM_TO_IN) |  |
| [M_TO_FT](M_TO_FT.qmd#pyslammer.M_TO_FT) |  |
| [M3_TO_CM3](M3_TO_CM3.qmd#pyslammer.M3_TO_CM3) |  |
| [LBFT3_TO_KNM3](LBFT3_TO_KNM3.qmd#pyslammer.LBFT3_TO_KNM3) |  |
| [KNM3_TO_LBFT3](KNM3_TO_LBFT3.qmd#pyslammer.KNM3_TO_LBFT3) |  |
| [BETA](BETA.qmd#pyslammer.BETA) |  |
| [GAMMA](GAMMA.qmd#pyslammer.GAMMA) |  |
| [Coupled](Coupled.qmd#pyslammer.Coupled) |  |
| [ca](ca.qmd#pyslammer.ca) |  |
| [sample_ground_motions](sample_ground_motions.qmd#pyslammer.sample_ground_motions) |  |
| [csv_time_hist](csv_time_hist.qmd#pyslammer.csv_time_hist) | Read a CSV file containing time history acceleration data and return a 1D numpy array and a timestep |